### ISSUE TITLE
upgrade s3scan?

### ISSUE THREAD

**Issue by emilymcafee** [mapbox/cloudfront-log-reader#25]
Background https://github.com/mapbox/cloudfront-log-reader/issues/24#issuecomment-230033084

gunzipping on the way down from S3 was added upstream in https://github.com/mapbox/s3scan/pull/14#issue-140786857. This removes the need for [`ScanGunzip`](https://github.com/mapbox/cloudfront-log-reader/blob/5fa0f7d6242b09e2f62aafe54b13bcae0fdf707a/index.js#L52-L66), and I believe it makes [`LogStream`](https://github.com/mapbox/cloudfront-log-reader/blob/5fa0f7d6242b09e2f62aafe54b13bcae0fdf707a/index.js#L33-L50) purely a wrapper of s3scan. Is that correct @yhahn ? If that's the case - should we remove reading functionality from this repo entirely (focus on prep instead), and recommend using s3scan directly?

**Comment by yhahn** [comment]
### Cleanup backlog

**Before**

```sh
cflogreader s3://bucket/some-prefix | generatepath cloudfront
```

**After**

```sh
s3scan s3://bucket/some-prefix --gunzip | generatepath cloudfront
```

This means that the streaming pieces that `cflogreader` used previously can now be removed:

- [ ] Remove + clean up `cflogreader`
  - https://github.com/mapbox/cloudfront-log-reader/blob/master/bin/cflogreader
  - Related lib streams/code
- [ ] Remove/update tests
- [ ] Test flow with `s3scan` to confirm all remaining functionality still works

------

### Renaming backlog

Then we'll be in a situation where we should probably rename this repo, since it's not reading any logs, just doing cool stuff with them if you stream them in.

`aws-log-replay` :sweat_smile: ?

- [ ] Decide on a new project name
- [ ] Rename
  - update project name in `package.json`
  - update docs/any other stray references
  - PR ^^
  - Merge + rename repo
- [ ] Travis
  - We will probably need to recreate the Travis AWS user + reencrypt the credentials since the old ones are tied to the old repo name
- [ ] Double check everything
- [ ] `npm publish` to create first package under new name!

cc @aarthykc @emilymcafee
